### ISSUE TITLE
Unable to Join GitHub Organization

### ISSUE THREAD

**Issue by ThisisXXZ** [nus-cs2113-AY2425S1/forum#10]
The invitation link on the course website does not seem to work for me.
![image](https://github.com/user-attachments/assets/042a4bfa-f41a-435c-996c-87a611419ebc)
Is anyone facing the same problem or is it because my account hasn't been registered for this course?

**Comment by okkhoy** [comment]
we haven't sent the invitations yet!!

**Comment by ThisisXXZ** [comment]
> we haven't sent the invitations yet!!

Got it. Thanks, professor!
