### ISSUE TITLE
Exercise 4.3: Ouput identical with expected output but testcase failed

### ISSUE THREAD

**Issue by kennethSty** [nus-cs2113-AY2425S1/forum#12]
The expected output of the task:
78
12
314
78
12
314
16

My output:
<img width="347" alt="image" src="https://github.com/user-attachments/assets/3a66d8c7-9404-44b2-a419-5e9f25c60223">

Why do I fail this test case? Are any specific whitespaces required? For reference: I print the area directly via System.out.println(s.area())

**Comment by DanLinhHuynh-Niwashi** [comment]
There is no white space required, I just directly printed it out just like you.

You may check if your output has an extra return or sth like that?

**Comment by jemehgoh** [comment]
Check your code for the Rectangle() and Circle() classes on Coursemology. Did you inherit from the Shape() class? (I had this problem with this exercise)

**Comment by skylee03** [comment]
In addition to public test cases, there are also hidden test cases. Your error may be caused by your OOP implementation not meeting the requirements, such as not having `extends Shape`.

**Comment by DanLinhHuynh-Niwashi** [comment]
If the program was successfully built, i think this may not the case.

As you store all of your instances in a list/ array of type Shape.
