### ISSUE TITLE
Admin Repo Link Week 4 not working

### ISSUE THREAD

**Issue by kennethSty** [nus-cs2113-AY2425S1/forum#13]
The [invitation link](https://github.com/orgs/nus-cs2113-AY2425S1/invitation.) in [the admin page of week 4 ](https://nus-cs2113-ay2425s1.github.io/website/schedule/week4/admin.html)to the org that we should join is not working:
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/28edcf15-10a7-4d96-a03f-94b33288567e">

**Comment by skylee03** [comment]
Duplicated with:
- #10
