### ISSUE TITLE
Regarding submission of UG on canvas

### ISSUE THREAD

**Issue by ryryry-3302** [nus-cs2113-AY2425S1/forum#19]
Hi may I know where the submission link can be found on canvas for this [deliverable](https://nus-cs2113-ay2425s1.github.io/website/schedule/week6/project.html#2-draft-the-ug-midnight-before-the-tutorial)
![image](https://github.com/user-attachments/assets/8dd2ca5b-29fb-4098-9cea-d95874963f5f)

**Comment by okkhoy** [comment]
It is scheduled to be open at 6 pm today.

**Comment by ryryry-3302** [comment]
I see thank you
