### ISSUE TITLE
Sourcetree cannot be opened on Mac

### ISSUE THREAD

**Issue by kennethSty** [nus-cs2113-AY2425S1/forum#2]
Translated Error Message when trying to open Sourcetree: 
_‘Sourcetree’ cannot be opened because Apple cannot search for malware in it.
This software needs to be updated. Contact the developer for more information._

Original Error Screenshot: 
<img width="302" alt="image" src="https://github.com/user-attachments/assets/7d3c9f88-efe6-4537-8db8-d7d0b8968679">

Machine Details: 

- MacOS BigSur
- Version: 11.5.2
- Chip: Apple M1

**Comment by AjayShanker-geek** [comment]
Another alternative method is that you could try installing through [homebrew](https://brew.sh) on mac.

```sh
# install homebrew package manger
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install sourcetree app
brew install --cask sourcetree

# open app
open -a "Sourcetree" # or open normally
```

Edit: Add homebrew url

**Comment by kennethSty** [comment]
Thanks Ajay! Unfortunately, I get the same error message.

**Comment by kennethSty** [comment]
Is it ok if I use the command line instead?

**Comment by ryryry-3302** [comment]
@kennethSty If im not wrong prof mentions that using entirely through CLI is fine over [here](https://nus-cs2113-ay2425s1.github.io/website/schedule/week1/admin.html#tool-git-for-revision-control) under Admin Tools - Git

You can find instructions on the command line setup [here](https://nus-cs2113-ay2425s1.github.io/website/schedule/week2/topics.html#tools-git-and-github-init-getting-started)

This disclaimer is also found at the bottom 2.7c
![image](https://github.com/user-attachments/assets/e3ffce99-65ce-4418-8a77-0e23c7c5aee0)

**Comment by AjayShanker-geek** [comment]
@kennethSty If you wanna try something else, TUI will be inbetween CLI & GUI. I personally use [lazygit](https://github.com/jesseduffield/lazygit) + neovim. 

If I am not wrong, Github Student Developer Pack will give free licence to [GitKraken](https://www.gitkraken.com/) which is GUI app. [LINK](https://education.github.com/pack)

Edit: Add link to Github education

**Comment by kennethSty** [comment]
Thanks everyone! I will stick to the Command Line then.

**Comment by okkhoy** [comment]
👍
