### ISSUE TITLE
Question about TP Constraints

### ISSUE THREAD

**Issue by Bev-low** [nus-cs2113-AY2425S1/forum#20]
Hi Prof, 

For our project we plan to have a file store our app data. We're thinking of also exporting a report to a seperate markdown file so there would be two seperate files being mantained by our app. Is it ok to have two files in our local directory at once? Thank you!

**Comment by okkhoy** [comment]
Yes, not a problem. However, having multiple versions mean that you need to put additional effort to maintain data consistency.
