### ISSUE TITLE
Testing code style conformity

### ISSUE THREAD

**Issue by kennethSty** [nus-cs2113-AY2425S1/forum#22]
Is it possible to use the grader's coding style checker before submitting the final version of the IP to ensure nothing is overseen? 

Would be very helpful!

**Comment by okkhoy** [comment]
You can include the tP's checkstyle to check coding style/standards:
https://github.com/nus-cs2113-AY2425S1/tp/tree/master/config/checkstyle
The iP repository by default doesn't have checkstyle configured.

**Comment by kennethSty** [comment]
Great thanks! @okkhoy how can I use this? ^^

**Comment by okkhoy** [comment]
Install checkstyle plugin for idea (file->setting->plugin ---> search for checkstyle and install checkstyle-idea)
Copy over the` config/` folder to your project similar directory structure as tP.
In IntelliJ file->setting ---> search for checkstyle and add the config/checkstyle.xml to the list and select it.
![image](https://github.com/user-attachments/assets/66632eff-ec32-49af-a5c5-e8a649a48cff)
Then you can run checkstyle to check for errors

**Comment by kennethSty** [comment]
Thanks!
