### ISSUE TITLE
Usage of final variables

### ISSUE THREAD

**Issue by averageandyyy** [nus-cs2113-AY2425S1/forum#23]
Hi Prof, I understand for constants we can use `public static final String MESSAGE` (as an example) to denote that this is a constant for better readability and reusability. Occasionally however, IntelliJ prompts that certain `private` variables can also be made `final`. Firstly, why does it do that and is there any merit to doing so? Is it due to some optimizations knowing that that variable would not be altered anymore? Secondly, in line with the class' coding standards, are we required to capitalize these variables? i.e. `private final String name = "name"` to `private final String NAME`

Thank you for the help!

**Comment by okkhoy** [comment]
I am not aware of any specific compiler-level optimizations that would suggest variable to be made final. It could be as you said - the variable may not be altered anymore in the code. (I suspect this is more like static analysis found that variable is not altered and IntelliJ is suggesting to make it final)

if it is a private final variable you can treat this as a constant and name it like a constant.

**Comment by averageandyyy** [comment]
I tried doing so, but the CS2113 checkstyle is sounding off and saying I should stick to the regular naming conventions as per what I have I been doing, that is, naming `private final` variables like non-constants. Should I proceed to rename them as constants or would it be fine if I preserved the old namings?

**Comment by okkhoy** [comment]
hmm... i think the checkstyle particularly looks for public static final for constants. 
proceed with naming as non-constants.

**Comment by averageandyyy** [comment]
Will do, thanks for the help Prof! :)
