### ISSUE TITLE
Question about A-MoreOOP increment

### ISSUE THREAD

**Issue by KSanjith** [nus-cs2113-AY2425S1/forum#24]
Dear Prof and TAs, I would like to ask whether it is **compulsory to create new Ui and Storage objects** in Main, and use those objects throughout the rest of the iP? Or instead, can the **Ui and Storage classes comprise purely of static methods** that are called as and when needed, **without** having to create the Ui and Storage objects and passing them around? Thank you.

**Comment by okkhoy** [comment]
From learning point of view, please create the classes and pass objects around.

**Comment by xenthm** [comment]
Hi Prof, will we be penalised if we make these classes utility classes (only static methods without instantiating as mentioned). I just came across this issue today.
