### ISSUE TITLE
Rebasing when syncing personal forks for tP

### ISSUE THREAD

**Issue by xenthm** [nus-cs2113-AY2425S1/forum#25]
[Appendix E: Using GitHub](https://nus-cs2113-ay2425s1.github.io/website/admin/appendixE-gitHub.html#d-using-prs-to-track-task-progress) instructs us to avoid rebasing when when merging PRs. 

Can we do that when managing our own fork instead? The goal is to keep our fork commit history cleaner.

**Comment by okkhoy** [comment]
Would it not affect the branches you create further and create PRs from? I don't have personal experience doing this (rebase fork vs not the upstream), so I can't give a definitive answer 🙁

**Comment by xenthm** [comment]
> Would it not affect the branches you create further and create PRs from?

Yes, my understanding is that it will reduce the clutter on my fork as a result of merge commits from other PRs from upstream. 

That being said, I think that that will cause issues when I create my own PRs since my fork's commit history will be different from the upstream's.

**Comment by okkhoy** [comment]
>  I think that that will cause issues when I create my own PRs since my fork's commit history will be different from the upstream's.

this is what I was alluding to, and I don't have personal experience doing this.

**Comment by xenthm** [comment]
Alright, I will stick with merging then. 

> avoid rebasing when when merging PRs

As for this, am I right to say that the motivation is to ensure that the automated checks for tP progress work as intended?

**Comment by okkhoy** [comment]
Yes, that is correct, as stated in the site.

**Comment by xenthm** [comment]
Thank you Prof!
