### ISSUE TITLE
Preferred way to add JUnit tests to repository

### ISSUE THREAD

**Issue by sarahchow03** [nus-cs2113-AY2425S1/forum#26]
If I have submitted a pull request for a particular feature and closed the issue, but have yet to write JUnit tests for it, is there a standard convention for me to follow to add said JUnit tests into the repository?

For instance, submit an issue "JUnit tests for add member function", and submit a PR for the issue for JUnit tests only.
Moving forward, is it better for me to do all tests and documentation in its related issue? Or is splitting them up into smaller increments (issues) a better strategy?

**Comment by okkhoy** [comment]
> or instance, submit an issue "JUnit tests for add member function", and submit a PR for the issue for JUnit tests only.

This is a good approach.

>  is it better for me to do all tests and documentation in its related issue? Or is splitting them up into smaller increments (issues) a better strategy?

There is no requirement from the course perspective for this. However, keeping things smaller is always better,

**Comment by sarahchow03** [comment]
Thank you Prof! Will take note of this.
