### ISSUE TITLE
Excessive emails from Archipelago

### ISSUE THREAD

**Issue by xenthm** [nus-cs2113-AY2425S1/forum#3]
Archipelago sends excessive Session Invitation emails with an invite link to the Lecture Session. Refer to the screenshot below. 

![image](https://github.com/user-attachments/assets/85a79af1-c9aa-4ca0-876d-82158d663dc0)

**Comment by DanLinhHuynh-Niwashi** [comment]
I think it should be okay, the session will be opened on time (it did last week). That might be some kind of bugs on Archipelago i guess.

**Comment by Sukkaito** [comment]
I have the same problem too, for now I'll probably just create a rule for Outlook to move invitations to a folder/subfolder.

FYI, create a new folder on Outlook, go to ```Settings -> Rules -> Add new rule```. Filter all emails from noreply@archipelago.rocks and remember to tick "Run rule now" (Modify the exception and different settings if you want). Then ```Save```.

All the invitation emails should go to the folder you've created, just remember to pin or put it somewhere for you to know if there is any update.

![image](https://github.com/user-attachments/assets/b7f56b82-212c-4f05-b589-2ad333b5132d)

**Comment by okkhoy** [comment]
Thanks for letting me know, folks. 
I have reached out for help. Hopefully, it will be resolved soon.

**Comment by xenthm** [comment]
Thank you Prof! Will monitor on Friday before the lecture.

**Comment by xenthm** [comment]
I received only 3 emails this time. Big improvement from last week haha. I will close the issue now!
