### ISSUE TITLE
Questions regarding UML diagrams

### ISSUE THREAD

**Issue by xenthm** [nus-cs2113-AY2425S1/forum#33]
# 1. Do UML Object Diagrams require that their associations show navigability from the corresponding class diagram?
Referring to the 2nd question in L8-Exercises, the object diagram from the answer that corresponds to the class diagram mirrors the navigability of the association between `Book`, and `ISBN` and `CallNumber`. However, I couldn't find any mention of this from the notes over at [`Object Diagrams → Associations`](https://nus-cs2113-ay2425s1.github.io/website/se-book-adapted/chapters/uml.html#associations-2). 
>Class Diagram from L8-Exercises ![image](https://github.com/user-attachments/assets/7ce74b01-e3e8-49aa-a895-6279cba52b49)
>Object Diagram answer from Canvas video ![image](https://github.com/user-attachments/assets/afde91e5-0f3f-402a-8b69-268c43baa327)
# 2. Does the existence of multiplicity imply navigability?
Referring to the 2nd question in L8-Exercises, the association class `Loan` has the multiplicity `1` indicated on both ends of the dashed line that connects to the association link between `Book` and `Student`. How do we know that `Loan` has references to <ins>both</ins> `Book` and `Student` (aside from reasoning with the desired associations with common sense)?
>Class Diagram from L8-Exercises ![image](https://github.com/user-attachments/assets/fbdf10ec-4d4e-493a-a2e2-b278a2851030)
>Object Diagram answer from Canvas video ![image](https://github.com/user-attachments/assets/a56a38c9-5a7a-4e52-b4fe-3c2f81a5562a)

**Comment by okkhoy** [comment]
Q1: When corresponding class diagram is available, navigability can be inferred; if not, better to show it. Look under navigability where we say navigability applies to class or object diagrms
Q2: In the same video, I explained how we can translate the association class from one representation to the other (using A, B, C as classes); using that form, we can say loan has reference to both book and student. In my explanation, however, I did not mention about the mandatory multiplicity.

**Comment by xenthm** [comment]
Noted for Q1, thank you! As for Q2, I saw the video and noted that `Loan` has references to both `Book` and `Student`. To clarify my question, is it safe to assume that as long as we have an association class like `Loan`, it means we should represent it in the way in the video?
![image](https://github.com/user-attachments/assets/e8fc9d60-d2e1-46de-a273-18b716d27292)

A follow-up question to Q2 regarding multiplicity: If we see the number of multiplicity on one side of an association link that wasn't drawn with navigability (like how `Loan` is represented in the screenshot under Q2 in my previous comment, does that mean that there is navigability too? In other words, if we see a number should there be a reference from the base class?

**Comment by okkhoy** [comment]
>  is it safe to assume that as long as we have an association class like Loan, it means we should represent it in the way in the video?

Yes. that is the equivalent representation.

For association class, the multiplicity is always 1; it records details about that particular association. 
(but I am not sure I understood your question fully!)

**Comment by xenthm** [comment]
Here's a diagram for the last question. Does the one on top imply the one on the bottom?
![image](https://github.com/user-attachments/assets/c2a61467-4c78-4447-b764-58c3f9554019)

**Comment by okkhoy** [comment]
No!
For example:
![image](https://github.com/user-attachments/assets/4f48ec93-02da-4552-a46b-d9c2d5cc934a)

**Comment by xenthm** [comment]
I understand, thank you Prof!
