### ISSUE TITLE
Used-JUnit tag changed from green to red

### ISSUE THREAD

**Issue by KSanjith** [nus-cs2113-AY2425S1/forum#34]
Every member of the group CS2113-W13-1 had authored JUnit tests individually and successfully merged their PRs, which turned the Used-JUnit tag on all of their individual tp dashboards green. However, after a group member re-packaged the J-Unit files (without altering the code) and merged that PR, the JUnit tags for all the other group members turned red. We would like to ask how we can rectify this issue and return the tag to green?

**Comment by okkhoy** [comment]
add more junit tests. we check for junit every week. so it will go green again.
