### ISSUE TITLE
Pushed file is not updated

### ISSUE THREAD

**Issue by Bev-low** [nus-cs2113-AY2425S1/forum#8]
Hi I am using Intellij for my Ip project and am trying to push my files into the remote repositary. I used CLI to make commits, make a tag and push. There is a successful push with the tag name. However, when I check my files, there is no update from it. 

When I check my commits using Git Log, I can see that the commits are there. When I check Git Status, it says "Your branch is up to date with 'origin/master'." I did use force commit so my main file in my IP repo is up to date with my code. However, the tagged files are not up to date. I am unsure what is the issue here, my changes are not being saved. 

Link to Level-1 tag https://github.com/Bev-low/ip/releases/tag/level-1
Link to Level-0 tag https://github.com/Bev-low/ip/releases/tag/level-0
Both tags contains the same files

Thank you for your help.

**Comment by skylee03** [comment]
You probably want to move the tag `Level-1` to the correct commit (both locally and remotely). A discussion from a previous session of CS2103 may be helpful to you:
- nus-cs2103-AY2021S2/forum#36

**Comment by Bev-low** [comment]
Oh it works now, thank you so much!
